HERA-Team/hera_pspec

hera_pspec/__init__.py
hera_pspec/pspecdata.py
hera_pspec/tests/test_pspecdata.py

Refactors the `DataSet` class into a new `PSpecData` class. This now accepts a list of `UVData` objects as input. Documentation has been added for all methods and keywords, and the previous API has been changed slightly.
In changing to use `UVData` objects, the class no longer has its own internal data structure for the input data and weights. It just provides a thin wrapper on top of the `UVData.get_data()` method.
Some partially-implemented or obsolete features have been removed.
This is a partial implementation. Tests and some extra handling of lists of baseline keys is needed.

Refactor DataSet class into PSpecData class

---

.gitignore
hera_pspec/pspecbeam.py
hera_pspec/pspecdata.py
hera_pspec/tests/test_pspecbeam.py

There are a few bugs in `pspecbeam` I found while fixing one particular bug. These include
1. All `np.linspace()` calls should have `endpoint=False`, which is actually my fault for the confusion from the previous PR where I said the opposite.
2. `aipy` is not loaded in the module even though there is an `aipy` dependence when using a `taper` kwarg that is non-default.
3. `num_freqs` directly clashes with `num_steps`, which causes a broadcasting error when specifying a non-default `taper`. `num_freqs` is otherwise not used, so it is eliminated from the module.
4. With the above updates, the pspec scalar convergence test does not actually converge at only 20000 num_steps for some reason, not even close, even though this test was passing before. Not sure why this is the case, but I did a …

Fixed bugs in pspecbeam

---

hera_pspec/conversions.py
hera_pspec/pspecbeam.py
hera_pspec/tests/test_conversions.py
hera_pspec/tests/test_pspecbeam.py

for converting visibilities on a Jy scale to units of mK. Although ideally this would be done for us in the calibration step, in actuality the analysis team has no plan to give us visibilities on a mK scale, and also we developed the framework for calculating beam scalars in `hera_pspec` (which `hera_cal` does not have), so it makes sense for this conversion factor to go here...

added Jy_to_mK conversion method to pspecbeam

---

hera_pspec/pspecbeam.py
hera_pspec/pspecdata.py
hera_pspec/tests/test_pspecbeam.py
hera_pspec/tests/test_pspecdata.py

there were two calls to a tapering function in `pspecdata`, one in `get_Q` which is applied to the `Q` FT matrix, and another in `q_hat` which is applied directly to the data. Eliminating the one in `get_Q` makes OQE match the results Aaron P and I cooked up a few weeks ago, meaning that with these pushes I think OQE is properly normalized! 
Comparison with w/o tapering function (before fix)
Comparison with tapering function (before fix)
Comparison with tapering function (after fix, title should read `fix_extra_taper_fnc_get_Q`, not `master`)

Fix extra taper fnc get q

---

hera_pspec/noise.py
hera_pspec/pspecbeam.py
hera_pspec/pspecdata.py
hera_pspec/tests/test_noise.py
hera_pspec/tests/test_pspecbeam.py
hera_pspec/uvpspec.py

In accordance w/ recent `pyuvdata` PR, this PR updates all references to `pseudo_stokes` pol to just `stokes` pol (i.e. `pseudo_I` -> `I`).

changed "pseudo_stokes" to just "stokes" across the repo

---

setup.py

Simple patch to require certain version numbers of scipy and numpy packages at install time; fixes Issue #76.

Add install_requires lines to setup.py

---

examples/PSpecBeam_tutorial.ipynb
hera_pspec/__init__.py
hera_pspec/pspecbeam.py
hera_pspec/tests/test_pspecbeam.py

Adds new `PSpecBeamFromArray` object that lets users build `PSpecBeam` objects from a set of arrays. Based on suggestion from Nick and Ridhima in issue #79.
This PR will also include an example Jupyter notebook.

Allow users to build PSpecBeam objects from solid angle arrays

---

hera_pspec/pspecdata.py
hera_pspec/tests/test_pspecdata.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/uvpspec.py

Adds a new `labels` argument so datasets can be referred to using strings instead of indices if desired.
Also adds `__str__` function to PSpecData to allow pretty printing.

Add ability to name datasets in PSpecData

---

hera_pspec/pspecdata.py

which had default pol='I', but isn't passed a pol when called. pol is now an argument (rather than kwarg) to make this passing explicit

fixes minor bug in pspecdata.PSpecData.scalar

---

.travis.yml
hera_pspec/pspecbeam.py
hera_pspec/tests/test_noise.py
hera_pspec/tests/test_plot.py
hera_pspec/tests/test_pspecbeam.py

Recent changes to `pyuvdata` break some of our default strings. This fixes them, and removes a warning from matplotlib that has recently started showing up.

Update polarisation strings to new pyuvdata names

---

hera_pspec/pspecdata.py
hera_pspec/tests/test_pspecdata.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/uvpspec.py

addressing various 5/2018 DR comments, including uvp.get_blpairs func, doc string clarify and more informative assert in pspecdata, inversely averaging nsamp1 and nsamp2 in pspecdata.pspec(), and making Jy_to_mK a method on pspecdata.
Addresses issues #104, #105, #106, #111, and #115

minor upgrades to uvpspec and pspecdata

---

hera_pspec/__init__.py
hera_pspec/pspecdata.py
hera_pspec/testing.py
hera_pspec/tests/test_container.py
hera_pspec/tests/test_grouping.py
hera_pspec/tests/test_testing.py
hera_pspec/tests/test_utils.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/utils.py
hera_pspec/uvpspec.py
hera_pspec/uvpspec_utils.py

Adds `uvpspec.concat_uvp`, as well as reformats some of the meta-data in a `UVPSpec` obj in order to do so. Also adds `testing.py` w/ functions to build example `UVPSpec` objects

Adds concat_uvp to combine multiple UVPSpec objects

---

hera_pspec/uvpspec.py

modified:   hera_pspec/uvpspec.py
I was having problems using UVPSpec.write_to_group because label_1_array and label_2_array are too large to be written as an attr using HDF5, I was getting an "object header message is too large" error. I added them to _meta_dsets in order for them to be saved properly. A small change.

Added label_*_array to _meta_dsets

---

hera_pspec/pspecdata.py
hera_pspec/tests/test_pspecdata.py

This speeds up the q_hat computation, and hopefully reduces the memory footprint as well. @philbull, could you test with the test case you were trying the other day (the one that gave you a `MemoryError`). And please also make sure my `np.einsum` agrees with your expression? I think I got it right, and the tests confirm, but it's probably safest to check against what's on paper regardless.

Implemented q_hat speedup using broadcasted einsum

---

hera_pspec/tests/test_uvpspec.py
hera_pspec/uvpspec_utils.py

_select(uvp, bls=[...]) was returning a UVPSpec with the same bl_array as the original, even though it should have selected away baselines. Now it is selecting the right baselines from bl_array.
modified:   hera_pspec/uvpspec_utils.py

Fixed baseline select

---

.coveragerc
.travis.yml
MANIFEST.in
README.md
hera_pspec/container.py
hera_pspec/data/_test_utils.yaml
hera_pspec/grouping.py
hera_pspec/pspecdata.py
hera_pspec/testing.py
hera_pspec/tests/test_container.py
hera_pspec/tests/test_grouping.py
hera_pspec/tests/test_pipes.py
hera_pspec/tests/test_pspecdata.py
hera_pspec/tests/test_testing.py
hera_pspec/tests/test_utils.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/utils.py
hera_pspec/uvpspec.py
hera_pspec/uvpspec_utils.py
pipelines/idr2_preprocessing/preprocess_data.py
pipelines/idr2_preprocessing/preprocess_params.yaml
pipelines/pspec_pipeline/pspec_batch.sh
pipelines/pspec_pipeline/pspec_pipe.py
pipelines/pspec_pipeline/pspec_pipe.yaml
scripts/bootstrap_run.py
scripts/psc_merge_spectra.py
setup.py

This adds the
• `pipelines/pspec_pipeline/pspec_pipe.py` 
• `pipelines/pspec_pipeline/pspec_pipe.yaml`
• `pipelines/pspec_pipeline/pspec_batch.sh`
scripts as version 1 of the power spectrum pipeline, which goes through the analysis blocks in the following order:
1. Visibility data difference (e.g. for jacknives) [optional]
2. OQE pipeline
3. Bootstrap error pipeline
This branch should be merged __after__ the `stats_array` branch is merged in.
A statistical evaluation step seems appropriate for this script (after 3.) but due to circular dependency with `hera_stats` its not possible to add it in. We should make a `stats_pipe.py` script and `stats_pipe.yaml` script in `hera_stats/pipelines/stats_pipe` of similar format to perform this last step of the full power spectrum pipeline.
[UPDATE] …

power spectrum pipeline v1

---

hera_pspec/pspecdata.py

This is in regard to Issue #160

Changed default behaviour of exclude_auto_bls

---

hera_pspec/pspecdata.py
hera_pspec/testing.py
hera_pspec/tests/test_grouping.py
hera_pspec/tests/test_pspecdata.py
hera_pspec/tests/test_testing.py
hera_pspec/tests/test_utils.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/tests/test_uvpspec_utils.py
hera_pspec/utils.py
hera_pspec/uvpspec_utils.py
pipelines/idr2_preprocessing/preprocess_data.py
pipelines/idr2_preprocessing/preprocess_params.yaml
pipelines/pspec_pipeline/pspec_pipe.py
pipelines/pspec_pipeline/pspec_pipe.yaml

A few minor changes addressing issues in `UVPSpec` and `PSpecData` before we tag a release

Repo cleanup pretag

---

hera_pspec/plot.py
hera_pspec/tests/test_plot.py
hera_pspec/uvpspec.py
setup.py

Plot delay spectra ordered by time or baseline-pair. Solves #155.

Add ability to plot waterfalls of delay spectra

---

.travis.yml

currently HEAD of `master` (8/9/2018)

travis install pyuvdata commit 9c94be0366eb41692f55

---

hera_pspec/tests/test_utils.py
hera_pspec/utils.py

Now, `filter_blpairs` not only identifies flagged ants and filters them, but also looks at the actual `bls` in uvd1 and uvd2 and filters the output `blps` list on what's present before returning. This solves a bug for a special case where the user has selected out some of the baselines associated w/ an antenna, but not all. If the latter is done, than the xant filtering solves this issue up front.

Filtering fix for utils.calc_blpair_reds

---

hera_pspec/pspecdata.py
hera_pspec/tests/test_pspecdata.py

Fixed a minor bug where the `spw_ranges` kwarg of `pspec_run` wasn't being propagated to its call to `broadcast_dset_flags`. Added a test to ensure this is done correctly, and in general tidied up and clarified the various tests in `test_pspec_run` function.

fixed bug in pspec_run.broadcast_dset_flags and incr test cvrg

---

.travis.yml
examples/Bootstrap_example.ipynb
hera_pspec/tests/test_grouping.py
hera_pspec/tests/test_pspecdata.py
hera_pspec/tests/test_testing.py
hera_pspec/tests/test_utils.py
hera_pspec/utils.py
scripts/pspec_red.py

This follows https://github.com/HERA-Team/hera_cal/pull/370 and shouldn't be merged in until that PR is done.

Remove references to deprecated `low_hi` option for get_reds

---

hera_pspec/plot.py
hera_pspec/testing.py
hera_pspec/tests/test_grouping.py
hera_pspec/tests/test_noise.py
hera_pspec/tests/test_plot.py
hera_pspec/tests/test_testing.py
hera_pspec/uvpspec.py

Adds a `noise_sim` function to simulate uncorrelated gaussian noise, and to help validate the `noise.py` and `grouping.py` code. Specifically it serves as a simple validation test of
1. our `P_N` code in `noise.py`
2. our bootstrap errorbar code (averting the correlated-blpair bias by taking auto-blpair spectra) in `grouping.py`

Noise sim validation

---

.travis.yml
hera_pspec/tests/test_utils.py
hera_pspec/uvpspec_utils.py

(1) Fixes a problem with `UVPSpec.select()` assigning data arrays from the wrong spectral windows when `spws` is not `None`.
(2) Fixes issue with polstr conversion in `select()`.
(3) Fixes unit test failure caused by change in ordering of bl tuple elements.

Fix problems with spw select and polstr

---

.travis.yml
hera_pspec/container.py
hera_pspec/conversions.py
hera_pspec/grouping.py
hera_pspec/plot.py
hera_pspec/pspecbeam.py
hera_pspec/pspecdata.py
hera_pspec/pstokes.py
hera_pspec/testing.py
hera_pspec/tests/test_container.py
hera_pspec/tests/test_conversions.py
hera_pspec/tests/test_grouping.py
hera_pspec/tests/test_noise.py
hera_pspec/tests/test_plot.py
hera_pspec/tests/test_pspecbeam.py
hera_pspec/tests/test_pspecdata.py
hera_pspec/tests/test_testing.py
hera_pspec/tests/test_utils.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/tests/test_uvpspec_utils.py
hera_pspec/tests/test_version.py
hera_pspec/utils.py
hera_pspec/uvpspec.py
hera_pspec/uvpspec_utils.py
hera_pspec/version.py
setup.py

This PR enables cross-polarisation support, subject to the limitation that the beam scalar can't be computed for cross-pol yet. (In other words, this PR only allows unnormalised cross-pol spectra to be computed.)
The main change in the PR is to store polarisation pairs inside `UVPSpec`, instead of individual polarisations. Pol-pairs can be specified as tuples, e.g. `('xx', 'xx')`, or as specially-constructed integers (there are helper functions to deal with these). Individual polarisations (e.g. `'xx'`) are no longer accepted.
I also got a bit carried away and enabled Python 3 support in this PR. This required more extensive changes than first expected, as functions like `map()` and `reduce()` have been deprecated (now replaced with list comprehensions and `np.reduce`), some string …

Enable cross-pol power spectra *and* Python 3 support

---

.travis.yml
hera_pspec/uvpspec.py
setup.py

Fix two backwards compatibility bugs related to loading old HDF5 files into `UVPSpec` objects.
The first is related to HDF5 in Py3, which returns `bytes` instead of strings. A string comparison was failing as a result. All string attributes in `UVPSpec` files are now converted from `bytes` to strings.
The second is due to the recent change from `pol_array` to `polpair_array` in the `UVPSpec` data model. The old `pol_array` attribute is now detected and automatically converted to a `polpair_array` when a file is loaded. A `UserWarning` is shown when this happens.

Fix backwards compatibility bugs with UVPSpec data files

---

hera_pspec/pspecdata.py
hera_pspec/utils.py

I noticed a couple of instances where functions were giving poor or confusing feedback when the wrong (or mis-formatted) arguments were passed. I changed them to give more useful feedback to the user, and also updated some docstrings.
I also allowed users to set `wgts=None` when initialising `PSpecData` objects (which causes all weights to be set to whatever the flags are in the input `UVData` objects), and allowed the `baseline_tol` kwarg to be user-specified in the `pspec()` method, as it was previously hard-coded to `1.0` (this number is passed to the `validate_blpairs()` method).

Minor tweaks to improve error handling if arguments are in the wrong format

---

hera_pspec/noise.py
hera_pspec/tests/test_noise.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/uvpspec.py

__Minor updates__
1.) This updates how the sqrt(2) factor is propagated in our `P_N` calculation to make it more clear to the user. Before this was done only at the highest level, class method `UVPSpec.generate_noise_spectra` via the `real=True` kwarg. Now this is done at the lowest level, `noise.calc_P_N` function via the `component='real'` kwarg. The `component='real'` kwarg is then propagated through to the `generate_noise_spectra` method.
2.) This updates the metric we use to validate `P_N` in `test_noise.py` (RMS now instead of a standard deviation). the two are equivalent in this particular case (the reason why there was no test failure before), but the former is in principle more appropriate.

Noise test update

---

hera_pspec/grouping.py
hera_pspec/noise.py
hera_pspec/tests/test_grouping.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/uvpspec.py

added time-dependent PN in generate_noise

added time-dependent PN in generate_noise

---

hera_pspec/grouping.py

The `average_spectra` method requires blpairs to be specified as a list of lists at the moment, but it would be useful to also accept a list of ndarray too. This PR allows that.

Allow blpair groups to be passed as list of ndarray

---

hera_pspec/pspecdata.py

Straightforward labelling bug. Thanks very much to Matthieu Vilatte for his eagle eye!

Fix issue with antenna dict not being fetched from uvd2 in `pspecdata.validate_blpairs()`

---

README.md
docs/conf.py
hera_pspec/pspecbeam.py
hera_pspec/pspecdata.py
hera_pspec/tests/test_pspecdata.py
hera_pspec/uvpspec.py
setup.py

uvtools provides a much larger library of tapering functions than aipy, so our `PSpecData.taper` kwarg now draws from uvtools. One particular feature is the 7-term blackman harris window, which achieves more sidelobe suppression than the standard blackman harris window (aka 4-term blackman harris window). For users wanting to make power spectra of simulated FG + EoR datasets this may be necessary to achieve the required dynamic range. Addresses #221

pspec tapering functions draw from uvtools

---

hera_pspec/container.py
hera_pspec/pspecdata.py
hera_pspec/testing.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/uvpspec.py

Adds feature to optionally combine histories in `uvpspec.combine_uvpspec`. In the pspec pipeline, for example, keeping this on excessively duplicates the output file history, so we need a way to turn this off, which this PR does.
This also refactors the `combine_uvpspec` test where the `r_params` testing was thrown into the middle of the existing test: this PR pulls that apart into its own test for the sake of "atomic"-ness

Uvp combine history

---

examples/Inverse_sinc_weighting_example.ipynb
hera_pspec/pspecdata.py
hera_pspec/testing.py
hera_pspec/tests/test_pspecdata.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/tests/test_uvpspec_utils.py
hera_pspec/uvpspec.py
hera_pspec/uvpspec_utils.py

dspec.sinc_downweight_matrix now uses the more accurate "filter_half_width" keyword instead of "filter_width" which broke hera_pspec. This quick fix simply updates this keyword.

change filter_widths to filter_half_widths

---

hera_pspec/pspecbeam.py
hera_pspec/pspecdata.py
hera_pspec/pstokes.py
hera_pspec/tests/test_pspecdata.py
hera_pspec/uvpspec_utils.py

A recent `pyuvdata` update switched 'xx' and 'yy' to 'ee' and 'nn' with a definition of `x_orientation`, which H1C files now conform to. This caused some of our calls of `polstr2num` to break without propagating the `x_orientation` attribute. This PR propagates that attribute to fix this in the various regions where `polstr2num` is required.

updated calls to polstr2num w/ x_orientation

---

hera_pspec/grouping.py
hera_pspec/plot.py
hera_pspec/pspecdata.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/uvpspec.py

When wedge plotting sometimes the baseline ordering is mixed up, so the wedge well doesn't really look wedge-like. Realized this happens because in `uvp.get_blpairs()` we do `np.unique()` which automatically resorts the baselines not by their length but by their id, which can mess things up. So I made `uvp.get_blpairs()` do a unique without re-sorting and also enforced this ordering anyways in the wedge plotting function.

Fixes wedge plotting issue w/ baseline ordering

---

hera_pspec/uvpspec.py

Recent pyuvdata changes break an import in `uvpspec.py`. This simple PR renames the import appropriately.

Fix renamed pyuvdata import

---

hera_pspec/container.py
hera_pspec/pspecdata.py
hera_pspec/tests/test_utils.py
hera_pspec/utils.py

Brief PR: enables extra redundant group output from `utils.calc_blpair_reds` if requested. Usable by pspec pipe for redundant group handling.
To not break existing API, I made this output optional (default False)

extra_info kwarg to utils.calc_blpair_reds

---

environment.yml
hera_pspec/pspecdata.py
hera_pspec/testing.py
hera_pspec/tests/test_pspecdata.py
hera_pspec/uvpspec.py
hera_pspec/uvpspec_utils.py

Addresses #226  by providing a way to truncate data after filtering (i.e. the inverse covariance step) that so filtering can be applied across the full data bandwidth to reduce signal loss and provide better foreground isolation while the power spectrum is calculated from frequencies with ~equal redshift. 
Also address #227  by consolidating get_unnormed_V and cov_q_hat. cov_q_hat is now a wrapper for get_unnormed_V and both support functionality for calculating bandpower covariances from user supplied uvdata objects or empirically from the data itself. By converting cov_q_hat to a wrapper, get_unnormed_V is now subjected to same tests that original cov_q_hat was validated by, showing that the two independent calculations (by Jianrong and I) are equivalent (a good consistency check).

Band truncation after filtering and consolidated covariance calculations. 

---

hera_pspec/grouping.py
hera_pspec/pspecdata.py
hera_pspec/testing.py
hera_pspec/tests/test_grouping.py
hera_pspec/tests/test_pspecdata.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/uvpspec.py
hera_pspec/uvpspec_utils.py

This reverts the `test_uvp.h5` file back to its form in 8/2019, and makes the `window_function_array` attribute of `UVPSpec` a non-required parameter. 
This also addresses #256 : I was getting weird H matrices b/c I was not setting Ndlys after setting spw_range. We now automatically set Ndlys upon a `ds.set_spw()` call so this does not happen.
Another thing I'm finding in adding these tests is a failure in `get_MW` with `mode='V^-1/2'`. The eigenvector decomposition performed leads to some small but negative eigenvalues. There is a warning put in when this happens, but it doesn't do anything about the negative values--and the result is that `1/sqrt(eigvals)` creates nans that then get propagated to the M and W matrices. I fix this by truncating these eigenvectors before taking …

revert test_uvp to 8/2019. made window_func non-req

---

hera_pspec/pstokes.py
hera_pspec/tests/test_pstokes.py
hera_pspec/uvpspec.py

There was a pretty serious bug in `pstokes.construct_pstokes` where the right-hand polarization was not being selected properly from the input UVData object, see here #260.
Turns out this was only a problem when operating on multi-polarization files, which, while the code supported, was not being tested on, as at the time we used 1-pol files.
This PR fixes that bug and adds tests for the `construct_pstokes` method on our multi-pol files to catch this kind of bug going forward. Thanks @anguta for spotting this!

fixed pstokes multipol files construct_pstokes bug

---

hera_pspec/grouping.py
hera_pspec/tests/test_grouping.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/uvpspec.py

In `uvpspec.combine_uvpspec`, the optional attribute `stats_array` was not being propagated, even if it was filled by all input UVPSpec objects. This fixes that, and also asserts that for propagation of cov_array, all cov_model attributes of incoming uvps must match. Fixes #264

fixed stats_array propagation bug in combine_uvpspec

---

hera_pspec/container.py

Just editing docstrings I find confusing or misleading enough that I need to read the code as I use them.

Fix and clarify docstrings in pspec container

---

hera_pspec/pspecdata.py
hera_pspec/tests/test_pspecdata.py

a small typo that causes conjugated baseline to not be caught in pspec_run(). This is not a problem w/ any HERA data b/c baselines follow "low_hi" convention, but for simulated RIMEz data that do not conform to this, we found this bug. A unit test is added to ensure this is caught.

pspec_run blpair match typo

---

hera_pspec/tests/test_uvpspec.py
hera_pspec/uvpspec.py

This fixes an issue with power spectra folding. This is a short-term fix: there is an issue out to deprecate the "folding" behavior entirely, as it is quite opaque and can be more easily achieved with recent code added for spherical binning.

Fix the inconsistency on exchanging the order of folding and averaging power spectra

---

hera_pspec/tests/test_utils.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/utils.py
hera_pspec/uvpspec.py

This adds some tools for getting down selecting on projected east-west baseline length in the `utils.get_reds()` method, which operates on UVData files. 
I also added the method `uvp.get_blpair_blvecs()`, which returns the baseline vector of the baseline-pair array (matching the order of `uvp.blpair_array`).
Although a single function for down selecting on a uvp object is not provided, this method makes it fairly straightforward to do so as
```
blp_vecs = uvp.get_blpair_blvecs()
uvp.select(blpairs=[blp for i, blp in enumerate(uvp.get_blpairs()) if abs(blp_vecs[i][0]) > my_blcut])
```

added min_EW_cut option to get_reds

---

hera_pspec/pspecdata.py

The `pspec_run` function wasn't passing the `bl_error_tol` argument to `utils.calc_blpair_reds`. One-line fix.

Fix omitted bl_tol argument in call to utils.calc_blpair_reds

---

hera_pspec/grouping.py
hera_pspec/pspecdata.py
hera_pspec/tests/test_grouping.py
hera_pspec/utils.py
hera_pspec/uvpspec.py

This fixes some minor bugs in how metadata is propagated in our `spherical_average` and `combine_uvpspec` methods. 
- First, some of the `Nblpairts` arrays were not being down selected after spherical averaging (from Nblpairts -> Ntimes).
- Second, the when combining uvpspec objects the dly_array was being overwritten with a `fftfreq` call, which is only true if the pspectra have not been spherically averaged. This changes how the dly_array and freq_array are treated in the `combine_uvpspec` to simply propagate what's already in the input objects, which in hindsight is how we should have done this in the first place.
Tests are added to catch these bugs going forward...

metadata handling fixes in spherical_avg and combine_uvpspec

---

.github/workflows/ci.yml
hera_pspec/tests/test_container.py
hera_pspec/tests/test_conversions.py
hera_pspec/tests/test_grouping.py
hera_pspec/tests/test_noise.py
hera_pspec/tests/test_plot.py
hera_pspec/tests/test_pspecbeam.py
hera_pspec/tests/test_pspecdata.py
hera_pspec/tests/test_pstokes.py
hera_pspec/tests/test_testing.py
hera_pspec/tests/test_utils.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/tests/test_uvpspec_utils.py
hera_pspec/tests/test_version.py

For reasons that are somewhat opaque to me, the existing pytest setup was not actually recording coverage (coverage files were produced, but all the lines were recorded as missed). By adjusting imports in the test files and removing a problematic arg, I think I've fixed this.

Fix issue where coverage isn't actually being recorded in coverage.xml (resulting in 0% coverage recorded by codecov).

---

hera_pspec/grouping.py

Closes #313 
Reduces memory footprint of spherical_average by a factor of nblpair by representing the Ndlyblpair x Ndlyblpair block-diagonal dimensions of the E matrix as an Ndlyblpair x Ndly matrix instead.
This also speeds up the matrix multiplication of E @ A by a factor of Nblpair (which dominates the matrix multiplication runtime for A^T @ E @ A.

spherical averaging acceleration.

---

hera_pspec/utils.py
hera_pspec/uvpspec.py

Closes #330 
`utils.uvp_noise_errors` now precomputes the normalization scalar before looping through blpairs. This avoids recomputing the noise scalar many times which significantly increases runtime.
loss in coverage is due to white space removal from an already uncovered line (so diff should actually be 100% covered).

Avoid recomputing noise scalars in `utils.generate_noise_errors`

---

setup.py

Replaced `git clone git://github.com/HERA-Team/uvtools` calls with `git clone https://github.com/HERA-Team/uvtools` to allow checks to run properly. Otherwise, throws git error.

Fix issue with git clone in setup.py

---

hera_pspec/tests/test_noise.py
hera_pspec/utils.py

Small modification to `uvp_noise_errors` to allow for noise calculation in files with a single time.

Handle single time noise files

---

hera_pspec/utils.py

Fix bug in `P_SN` correction calculation where nans can be introduced if both P_N and P_SN are infinite. If this is the case, then P_SN should still be np.inf after correction but instead it is set to Nan since the calculation takes the ratio between P_N and P_SN and numpy assigns inf/inf=nan (offending line is at https://github.com/HERA-Team/hera_pspec/blob/e6b73604ed771b6c1d56b4cf0396ccda2d56635d/hera_pspec/utils.py#L1514 ) 
This PR sets all nans introduced by this step to infinty.

get rid of nans from P_SN correction.

---

.github/workflows/ci.yml

Update tests workflow to `codecov` v3 and remove secret token (not required for public repos). Was causing checks to fail (only for macOS weirdly)

Fix issue running tests due to codecov version

---

hera_pspec/grouping.py
hera_pspec/plot.py
hera_pspec/pspecdata.py
hera_pspec/testing.py
hera_pspec/tests/test_grouping.py
hera_pspec/tests/test_noise.py
hera_pspec/tests/test_plot.py
hera_pspec/tests/test_uvpspec.py
hera_pspec/tests/test_uvpspec_utils.py
hera_pspec/utils.py
hera_pspec/uvpspec.py
hera_pspec/uvpspec_utils.py
hera_pspec/uvwindow.py

This PR addresses a current limitation in UVPspec class in that it addresses unique data samples with baseline pair and the average time of the two samples being crossed for a power spectrum sample. A common use case that comes up is when we cross two different times for the same baseline pair. For a concrete example, consider the baseline pair `(bl_0, bl_1)` where each baseline is sampled at two close-together times `t1, t2`. It is common practice to form interleaves between the times so that we form the baseline-time pairs, `(bl_0, t1) x conj((bl_1, t2))` and `(bl_0, t2) x conj((bl_1, t1))` Both of these power spectra have the same average-time (`t1/2 + t2/2`) and as a result, they cannot actually be stored in the same `UVPSpec` object. Currently `pspec_run` is forced to compute these …

Unique time-keys  in `UVPSpec` objects based on `time_1_array` and `time_2_array` instead of the current `time_avg_array`

---

.gitignore
hera_pspec/tests/test_noise.py
hera_pspec/tests/test_uvwindow.py
hera_pspec/utils.py
hera_pspec/uvwindow.py

This PR replaces a couple of lingering `freq_array[0]` with np.squeeze() which works for both past and future array shapes.
I've added a unit test that fails on the current main branch and passes (I hope!) on this branch. 
Finally, while searching the repo for `freq_array[0]` I found a couple of calculations of delta nu that aren't quite right (they take the middle freq of the first and last bin and divide by the number of bins, when really want you want to do is a diff... that calculation will be wrong by a factor of 2 in the limit where there are only 2 frequency channels). So I fixed those too.

Fix residual issues with future_array_shapes affecting noise calculation

---

.readthedocs.yaml
docs/requirements.txt

This PR deals with a new requirement from Readthedocs (see [link](https://blog.readthedocs.com/migrate-configuration-v2/)). It adds a `.readthedocs.yaml` file (version 2) listing the build requirements for the documentation as well as a `docs/requirements.txt` which lists the version of `sphinx` etc. required to build the documentation.

Added requirement files for readthedocs

---

hera_pspec/pspecdata.py
hera_pspec/tests/test_pspecdata.py

Currently the `pspec_run` command accepts `dsets` as a parameter, which is a list of UVData objects or string filepaths to UVData-compatible files. However, the acceptable UVData objects are implicitly using future_array_shape, which is not specified in the code. This PR aims to fix this issue.

Fixing pspec_run to allow the use of non-future-array-shape uvdata

---

hera_pspec/utils.py

The documentation of `utils.uvp_noise_error()` suggest that if "power spectra were computed from interleaved times then the supplied `auto_Tsys` should include all of the times that are present in all of the pairs." For interleaved power spectra, that the number of times in `auto_Tsys` (a `UVData` object) might be double (or more, for more interleaves) the number of times in `uvp.lst_avg_array`.
This creates a problem in the line 
```
Tsys = interp1d(lsts[~Tflag], Tsys[~Tflag], kind='nearest', bounds_error=False, fill_value='extrapolate')(lst_avg)
``` 
because `lsts` is calculated as
```
lst_indices = np.unique(auto_Tsys.lst_array, return_index=True)[1]
lsts = auto_Tsys.lst_array[sorted(lst_indices)]
```
while `Tflag` has a shape determined by the number of times in `uvp.time_1_array` and …

Fix uvp_noise_error() for interleaved LSTs

---

hera_pspec/pstokes.py

Proper combining of nsamples for psuedo-Stokes to preserve proper noise variance

---

.github/workflows/ci.yml
.readthedocs.yaml
docs/requirements.txt
setup.cfg

This PR adds two elements that were missing for the tests to pass:
- Adds a secret for `codecov`. Although it is not required for public repos, uploads often fail when you don't have one. If you don't set one, it uses like a backup public token which has a rate limit (@steven-murray)
- Adds the `mock` package as a requirement for the documentation: building `readthedocs` is failing without (called in `conf.py`)

Fix test errors: codecov secret and missing package for docs

---

.github/workflows/ci.yml
setup.cfg

This PR removes `python=3.8` from tests as there was a compatibility problem with `hera_cal` and `optax1` and added 3.11 and 3.12.

Change python version in tests

---

hera_pspec/tests/test_utils.py
hera_pspec/utils.py

Following @JianrongTan's issue #396 , this PR
1. Fixes a backward compatibility issue in `utils.uvd_to_Tsys` which raised an error when the `UVData` file used has `future_array_shapes=False`
2. Adds tests to `test_utils` to ensure backwards compatibility of the code with and without future array shapes.

Added tests re. future array shapes and ensured compatibility in utils

---

hera_pspec/tests/test_uvpspec.py
hera_pspec/uvpspec.py

This PR graduates a function that currently lives in both https://github.com/HERA-Team/hera_notebook_templates/blob/master/notebooks/single_baseline_postprocessing_and_pspec.ipynb and https://github.com/HERA-Team/hera_notebook_templates/blob/master/notebooks/power_spectrum_summary.ipynb
It is a somewhat faster way to combine large numbers of `uvpspec` objects using recursion, allowing fewer total adds to be performed.

Add recursive_combine_uvpspec()
